name: test21
favicon: null
layout_spectrum: 0.7849069670774043
typography_spectrum: 0.4363293556962162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.18691872037015855
  lightness: 0.43503796262666583
  saturation: 0.3201510179787874
  rhythmicContrast: 0.12455234513618052
purpose: []
